### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Anarchick** [Anarchick/skript-packet#7]
- [x] Field autoconverter for nms MinecraftKey from %entity/entitytype/material/itemstack/block/blockdata%
- [x] Fix async event cancelling default and sync
- [ ] More autoconverter %object% to NMS related of String 
- [ ] Is custom packet
- [ ] Listen all packet for X second and store result in variable list
- [ ] Add new fonctionalities from ProtocolLib 5.0.0
- [ ] Found a way to get biome nms id
- [ ] Add an expression using ProtocolLibrary.getProtocolManager()#getEntityTrackers()
- [ ] Add an expression using ProtocolLibrary.getProtocolManager()#isClosed()
- [ ] Add an expresion using MinecraftReflection#getBukkitPlayerFromConnection
- [ ] Found a way to get an inventory from windows Id
- [ ] Found a way to get player click id
- [ ] ExprNMS wrap RELATED_TO_STRING
- [ ] ExprNMS to NMS NBT
